<?php
declare(strict_types=1);

require_once __DIR__ . '/config.php';

$pdo = wadai_db();

$categories = [
    ['key' => 'omakase', 'label' => 'おまかせ', 'sort_order' => 0],
    ['key' => 'close_friends', 'label' => '友達', 'sort_order' => 1],
    ['key' => 'first_meeting', 'label' => '初対面', 'sort_order' => 2],
    ['key' => 'school', 'label' => '学校', 'sort_order' => 3],
    ['key' => 'romance', 'label' => '恋愛', 'sort_order' => 4],
    ['key' => 'date', 'label' => 'デート', 'sort_order' => 5],
    ['key' => 'funny', 'label' => '面白い', 'sort_order' => 6],
];

$topics = [
    // --- omakase ---
    ['key' => 'o1', 'body' => '最近、時間を忘れてハマったことは？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o2', 'body' => 'それを始めたきっかけは？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o3', 'body' => 'その中で一番好きなところは？', 'category' => 'omakase', 'depth' => 3],
    ['key' => 'o4', 'body' => 'それを始めてから、自分の中で変わったことはある？', 'category' => 'omakase', 'depth' => 4],
    ['key' => 'o5', 'body' => '子供の頃に好きだった遊びは？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o6', 'body' => '今もたまにやることある？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o7', 'body' => '最近買ってよかったものは？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o8', 'body' => 'どこで見つけたの？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o9', 'body' => '他に気になってるものある？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o10', 'body' => '最近、寝る前についつい開いちゃうアプリは？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o11', 'body' => 'そのアプリで一番時間溶かしたコンテンツは？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o12', 'body' => 'それを友達にもすすめたことある？', 'category' => 'omakase', 'depth' => 3],
    ['key' => 'o13', 'body' => '最近ハマってる曲、1曲だけ挙げるなら？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o14', 'body' => '何がきっかけでその曲を知ったの？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o15', 'body' => 'カラオケで歌う？', 'category' => 'omakase', 'depth' => 3],
    ['key' => 'o16', 'body' => 'スマホのホーム画面、一番目立つところに置いてるアプリは？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o17', 'body' => 'スクリーンタイムのランキング1位、何のアプリ？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o18', 'body' => '推し活してるものある？（アイドル・アニメ・スポーツ何でも）', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o19', 'body' => 'その良さ、ひとことで言うと？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o20', 'body' => '布教したくなる瞬間ってどんな時？', 'category' => 'omakase', 'depth' => 3],
    ['key' => 'o21', 'body' => '最近見て良かった動画・配信は？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o22', 'body' => 'それ、誰かに共有した？', 'category' => 'omakase', 'depth' => 2],
    // --- close_friends（友達） ---
    ['key' => 'c1', 'body' => '最近、地味に嬉しかったことは？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c2', 'body' => 'それって自分にとってどんな意味がある？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c3', 'body' => 'もし1年休みが取れたら何をしたい？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c4', 'body' => 'なんでそれをやってみたいと思ったの？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c5', 'body' => 'そのとき何を感じそう？', 'category' => 'close_friends', 'depth' => 3],
    ['key' => 'c6', 'body' => 'グループLINEで一番テンション上がるスタンプって何？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c7', 'body' => 'それ実際どんな時に使う？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c8', 'body' => '今の友達グループの中で自分ってどんなポジションだと思う？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c9', 'body' => 'そのポジション、自分でも気に入ってる？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c10', 'body' => '昔からそういうタイプだった？', 'category' => 'close_friends', 'depth' => 3],
    ['key' => 'c11', 'body' => '友達に地味に感謝してることある？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c12', 'body' => 'それ、ちゃんと言葉にして伝えたことある？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c13', 'body' => '最近、誰かに『わかる』って共感しまくったことは？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c14', 'body' => 'それ話したらどんな反応された？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c15', 'body' => '自分が一番落ち込んでる時、誰に連絡する？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c16', 'body' => 'その人のどんなところが安心する？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c17', 'body' => '自分もその人にとってそういう存在になれてると思う？', 'category' => 'close_friends', 'depth' => 3],
    // --- first_meeting ---
    ['key' => 'f1', 'body' => '出身はどのあたりですか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f2', 'body' => 'その土地ならではの好きなところは？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f3', 'body' => '休みの日は何をして過ごすことが多いですか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f4', 'body' => 'それを始めたきっかけは？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f5', 'body' => '好きな食べ物は？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f6', 'body' => '普段よく聴く音楽のジャンルは？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f7', 'body' => 'そのジャンルにハマったきっかけは？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f8', 'body' => '休みの日、朝は早い派？遅い派？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f9', 'body' => 'その時間、何して過ごすことが多い？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f10', 'body' => '初めて話す人にちょっと聞いてみたいこと、逆にありますか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f11', 'body' => '好きな食べ物とは逆に、ちょっと苦手な食べ物ってありますか？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f12', 'body' => '普段どんなSNSをよく見てますか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f13', 'body' => 'そこで最近ハマったコンテンツは？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f14', 'body' => '部活や委員会は何かやってますか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f15', 'body' => 'それを選んだ理由ってありますか？', 'category' => 'first_meeting', 'depth' => 2],
    // --- school（学校） ---
    ['key' => 's1', 'body' => '今、一番気合い入れてる学校行事って何？（文化祭・体育祭・修学旅行とか）', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's2', 'body' => 'そこで自分は何の担当してる（してた）？', 'category' => 'school', 'depth' => 2],
    ['key' => 's3', 'body' => '本番、どんな感じになりそう？', 'category' => 'school', 'depth' => 3],
    ['key' => 's4', 'body' => '部活や委員会で、今の一番の悩みってある？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's5', 'body' => 'それ、誰かに相談したことある？', 'category' => 'school', 'depth' => 2],
    ['key' => 's6', 'body' => 'テスト期間、直前になって焦るタイプ？コツコツやるタイプ？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's7', 'body' => 'テスト前日は何して過ごすことが多い？', 'category' => 'school', 'depth' => 2],
    ['key' => 's8', 'body' => '学校で一番好きな時間帯って授業中・休み時間・放課後のどれ？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's9', 'body' => 'その時間、大体何して過ごしてる？', 'category' => 'school', 'depth' => 2],
    ['key' => 's10', 'body' => '席替え、好きな方？苦手な方？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's11', 'body' => '理想の席の場所ってある？', 'category' => 'school', 'depth' => 2],
    ['key' => 's12', 'body' => 'クラスで地味に定番になってる『あるある』ネタってある？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's13', 'body' => '最近、授業中にこっそり考え事してたことある？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's14', 'body' => 'それ、先生にバレたことある？', 'category' => 'school', 'depth' => 2],
    ['key' => 's15', 'body' => 'お昼、どこで誰と食べることが多い？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's16', 'body' => 'そのメンバーになった経緯ってある？', 'category' => 'school', 'depth' => 2],
    ['key' => 's17', 'body' => '制服、自分なりにアレンジしてる部分ある？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's18', 'body' => '進路や将来のこと、今どのくらい考えてる？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's19', 'body' => 'そう思うようになったきっかけってある？', 'category' => 'school', 'depth' => 2],
    ['key' => 's20', 'body' => 'それ、親や先生に話したことある？', 'category' => 'school', 'depth' => 3],
    // --- romance（恋愛） ---
    ['key' => 'r1', 'body' => '好きな人ができると、まず変わることってどんなところ？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r2', 'body' => 'それ、自分で気づいてた？周りに指摘された？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r3', 'body' => 'それが一番当てはまったのっていつ頃？', 'category' => 'romance', 'depth' => 3],
    ['key' => 'r4', 'body' => '好きなタイプ、外見と中身どっちを先に見る？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r5', 'body' => 'その基準、いつ頃からそうなった？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r6', 'body' => '気になる人ができた時、最初にすることってある？（SNSチェックとか）', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r7', 'body' => 'それで印象変わったことある？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r8', 'body' => '告白は自分からするタイプ？されるの待つタイプ？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r9', 'body' => 'その理由、自分でどう説明する？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r10', 'body' => '好きな人とのLINE、既読の速さって気になる方？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r11', 'body' => 'それで一喜一憂したエピソードある？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r12', 'body' => '友達の恋愛相談、聞く方？する方？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r13', 'body' => '相談されて一番困った内容ってある？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r14', 'body' => '理想のデート、インドア派？アウトドア派？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r15', 'body' => '連絡の頻度、多い方が安心する？少なめでも平気？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r16', 'body' => 'それで気まずくなったことある？', 'category' => 'romance', 'depth' => 2],
    // --- date（デート） ---
    ['key' => 'd1', 'body' => '今日のこの後、正直もっとどこ行きたい気分？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd2', 'body' => 'そこを選んだ理由ってある？', 'category' => 'date', 'depth' => 2],
    ['key' => 'd3', 'body' => '今までのデートで一番良かった場所ってどこ？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd4', 'body' => '何がそんなに良かった？', 'category' => 'date', 'depth' => 2],
    ['key' => 'd5', 'body' => 'また同じ場所、行きたいと思う？', 'category' => 'date', 'depth' => 3],
    ['key' => 'd6', 'body' => '今度、一緒に行ってみたい場所ってある？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd7', 'body' => 'そこで何したい？', 'category' => 'date', 'depth' => 2],
    ['key' => 'd8', 'body' => 'デートの日の朝って、準備にどのくらい時間かける？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd9', 'body' => '一番気合い入れるのはどの部分？', 'category' => 'date', 'depth' => 2],
    ['key' => 'd10', 'body' => '映画・カフェ・遊園地、デートで一番好きなのはどれ？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd11', 'body' => 'その理由をひとことで言うと？', 'category' => 'date', 'depth' => 2],
    ['key' => 'd12', 'body' => '今日の格好、自分で採点するなら100点中何点？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd13', 'body' => '一緒にいて一番落ち着く瞬間ってどんな時？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd14', 'body' => 'それ、今日もあった？', 'category' => 'date', 'depth' => 2],
    // --- funny（面白い） ---
    ['key' => 'n1', 'body' => '今まで一番くだらない理由でケンカしたことは？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n2', 'body' => 'その時どっちが折れたの？', 'category' => 'funny', 'depth' => 2],
    ['key' => 'n3', 'body' => '人生で一番の黒歴史をひとつだけ挙げるなら？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n4', 'body' => '今思い出しても笑える？', 'category' => 'funny', 'depth' => 2],
    ['key' => 'n5', 'body' => 'スマホのスクショフォルダで一番謎な1枚、心当たりある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n6', 'body' => 'それ、何で保存したままなの？', 'category' => 'funny', 'depth' => 2],
    ['key' => 'n7', 'body' => '友達に一番いじられるポイントってある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n8', 'body' => 'それ、実は自分でも気に入ってたりする？', 'category' => 'funny', 'depth' => 2],
    ['key' => 'n9', 'body' => '今までで一番盛大な勘違いエピソードある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n10', 'body' => '気づいた瞬間、どうなった？', 'category' => 'funny', 'depth' => 2],
    ['key' => 'n11', 'body' => '自分の中の『あるある』で、誰にも共感してもらえないやつある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    // --- omakase ---
    ['key' => 'o23', 'body' => '最近、写真より動画で撮ることの方が増えた？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o24', 'body' => '残しておきたくなるのはどんな瞬間？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o25', 'body' => '1日の中でスマホを一番触ってる時間帯は？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o26', 'body' => 'その時間、大体何見てる？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o27', 'body' => '推し活してるなら、グッズって何か持ってる？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o28', 'body' => '一番のお気に入りのグッズはどれ？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o29', 'body' => 'それ、どこに飾ってる（しまってる）？', 'category' => 'omakase', 'depth' => 3],
    ['key' => 'o30', 'body' => '友達との写真や動画、どのアプリに一番残してる？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o31', 'body' => '見返すことある？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o32', 'body' => '最近バイトしてる？（したことある？）', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o33', 'body' => 'そのバイト選んだ理由ある？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o34', 'body' => '課金したことあるアプリやゲームある？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o35', 'body' => 'それ、今振り返ってどう思う？', 'category' => 'omakase', 'depth' => 2],
    ['key' => 'o36', 'body' => '最近、誰かに『それいいね』って言われて嬉しかったものある？', 'category' => 'omakase', 'depth' => 1, 'is_starter' => true],
    ['key' => 'o37', 'body' => '自分でも気に入ってるポイントなんだった？', 'category' => 'omakase', 'depth' => 2],
    // --- close_friends（友達） ---
    ['key' => 'c18', 'body' => '友達グループの裏話、実はここだけの話ってある？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c19', 'body' => 'それ、話してもいいやつ？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c20', 'body' => '友達に一番『助かった』って思った瞬間は？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c21', 'body' => 'それ、ちゃんとお礼言えた？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c22', 'body' => '友達とケンカした時、仲直りのきっかけになるのはどっちが多い？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c23', 'body' => '最近そういうことあった？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c24', 'body' => '今の友達と出会った瞬間、覚えてる？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c25', 'body' => '最初の印象と今で変わったことある？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c26', 'body' => 'その変化、自分でどう思う？', 'category' => 'close_friends', 'depth' => 3],
    ['key' => 'c27', 'body' => '友達といて一番自分らしくいられる瞬間ってどんな時？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    ['key' => 'c28', 'body' => '逆に、気を遣っちゃう瞬間もある？', 'category' => 'close_friends', 'depth' => 2],
    ['key' => 'c29', 'body' => '友達のことで、地味に尊敬してるところある？', 'category' => 'close_friends', 'depth' => 1, 'is_starter' => true],
    // --- first_meeting ---
    ['key' => 'f16', 'body' => '普段、写真や動画ってよく撮る方ですか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f17', 'body' => '最近見てハマった動画とかありますか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f18', 'body' => 'それ、どこで見つけたんですか？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f19', 'body' => 'バイトってしてますか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f20', 'body' => 'どんな感じのバイトですか？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f21', 'body' => '小さい頃から好きなものって、今も好きだったりしますか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f22', 'body' => '得意な科目とか、ありますか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f23', 'body' => 'それ、好きだから得意なんですか？', 'category' => 'first_meeting', 'depth' => 2],
    ['key' => 'f24', 'body' => '休日と平日、どっちのが好きですか？', 'category' => 'first_meeting', 'depth' => 1, 'is_starter' => true],
    ['key' => 'f25', 'body' => '平日はどんな感じで過ごしてますか？', 'category' => 'first_meeting', 'depth' => 2],
    // --- school（学校） ---
    ['key' => 's21', 'body' => 'クラスTシャツ（クラT）のデザイン、自分たちのはどんな感じ？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's22', 'body' => 'そのデザイン、自分の意見も反映された？', 'category' => 'school', 'depth' => 2],
    ['key' => 's23', 'body' => '文化祭・体育祭の打ち上げ、毎回行く方？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's24', 'body' => 'バイトと部活・委員会、両立できてる方？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's25', 'body' => 'スケジュール管理ってどうやってる？', 'category' => 'school', 'depth' => 2],
    ['key' => 's26', 'body' => 'クラスのグループ、通知ずっと見ちゃう方？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's27', 'body' => '模試や定期テストの結果、親には見せる派？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's28', 'body' => '見せた時、大体どんな反応される？', 'category' => 'school', 'depth' => 2],
    ['key' => 's29', 'body' => '学校の中で密かに気に入ってる場所ってある？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's30', 'body' => '委員会や係、今何かやってる？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's31', 'body' => 'それ、自分から立候補した？', 'category' => 'school', 'depth' => 2],
    ['key' => 's32', 'body' => '学校行事で一番記憶に残ってるのはどれ？', 'category' => 'school', 'depth' => 1, 'is_starter' => true],
    ['key' => 's33', 'body' => 'その時、自分はどんな役割だった？', 'category' => 'school', 'depth' => 2],
    // --- romance（恋愛） ---
    ['key' => 'r17', 'body' => '好きな人ができたこと、友達に話す方？内緒にする方？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r18', 'body' => '話すとしたら、まず誰に話す？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r19', 'body' => 'プロフィール画像やアイコン、気分で変える方？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r20', 'body' => 'デートした後、その日のうちに連絡する派？時間空ける派？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r21', 'body' => 'それ、相手にも同じようにしてほしいタイプ？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r22', 'body' => '記念日とか、ちゃんと覚えてる方？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r23', 'body' => 'カップルでお揃いのもの、持ちたい派？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r24', 'body' => '相手のどんな連絡が来ると安心する？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r25', 'body' => '逆に、ちょっと不安になる連絡ってある？', 'category' => 'romance', 'depth' => 2],
    ['key' => 'r26', 'body' => '好きな人の前とそれ以外で、自分の態度って変わる方？', 'category' => 'romance', 'depth' => 1, 'is_starter' => true],
    ['key' => 'r27', 'body' => 'それ、意識してやってる？無意識？', 'category' => 'romance', 'depth' => 2],
    // --- date（デート） ---
    ['key' => 'd15', 'body' => '今日、写真とか撮った？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd16', 'body' => '一番のお気に入り、どれ？', 'category' => 'date', 'depth' => 2],
    ['key' => 'd17', 'body' => 'デート中、無言の時間って気になる方？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd18', 'body' => '今日食べたもので一番おいしかったのは？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd19', 'body' => '絶叫系とか、得意な方？苦手な方？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd20', 'body' => '今度もし1日フリーで一緒に過ごせるなら、何して過ごしたい？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd21', 'body' => '待ち合わせ、早めに着く方？ぴったり派？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd22', 'body' => '今日のデート、自分の中で何点？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    ['key' => 'd23', 'body' => 'その点数の理由、聞いてもいい？', 'category' => 'date', 'depth' => 2],
    ['key' => 'd24', 'body' => '次また会えるとしたら、いつ頃がいい？', 'category' => 'date', 'depth' => 1, 'is_starter' => true],
    // --- funny（面白い） ---
    ['key' => 'n12', 'body' => 'グループ通話中に起きたハプニング、なんかある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n13', 'body' => 'その場、どんな空気になった？', 'category' => 'funny', 'depth' => 2],
    ['key' => 'n14', 'body' => 'TikTokやリールの真似して失敗したことある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n15', 'body' => '家族に見られて気まずかったスマホの中身、なんかある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n16', 'body' => '送信先間違えたLINE、送ったことある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n17', 'body' => 'それ、どうやってごまかした（対処した）？', 'category' => 'funny', 'depth' => 2],
    ['key' => 'n18', 'body' => '学校で一番『やらかした』と思う瞬間ある？', 'category' => 'funny', 'depth' => 1, 'is_starter' => true],
    ['key' => 'n19', 'body' => '今思うと、それも黒歴史の一つ？', 'category' => 'funny', 'depth' => 2],
];

$relations = [
    // --- omakase ---
    ['from' => 'o1', 'to' => 'o2', 'type' => 'deepen'],
    ['from' => 'o2', 'to' => 'o3', 'type' => 'deepen'],
    ['from' => 'o3', 'to' => 'o4', 'type' => 'deepen'],
    ['from' => 'o5', 'to' => 'o6', 'type' => 'deepen'],
    ['from' => 'o7', 'to' => 'o8', 'type' => 'deepen'],
    ['from' => 'o7', 'to' => 'o9', 'type' => 'deepen'],
    ['from' => 'o10', 'to' => 'o11', 'type' => 'deepen'],
    ['from' => 'o11', 'to' => 'o12', 'type' => 'deepen'],
    ['from' => 'o13', 'to' => 'o14', 'type' => 'deepen'],
    ['from' => 'o14', 'to' => 'o15', 'type' => 'deepen'],
    ['from' => 'o16', 'to' => 'o17', 'type' => 'deepen'],
    ['from' => 'o18', 'to' => 'o19', 'type' => 'deepen'],
    ['from' => 'o19', 'to' => 'o20', 'type' => 'deepen'],
    ['from' => 'o21', 'to' => 'o22', 'type' => 'deepen'],
    ['from' => 'o1', 'to' => 'o5', 'type' => 'related'],
    ['from' => 'o5', 'to' => 'o1', 'type' => 'related'],
    ['from' => 'o1', 'to' => 'o7', 'type' => 'related'],
    ['from' => 'o7', 'to' => 'o1', 'type' => 'related'],
    ['from' => 'o10', 'to' => 'o13', 'type' => 'related'],
    ['from' => 'o13', 'to' => 'o10', 'type' => 'related'],
    ['from' => 'o13', 'to' => 'o18', 'type' => 'related'],
    ['from' => 'o18', 'to' => 'o13', 'type' => 'related'],
    ['from' => 'o18', 'to' => 'o21', 'type' => 'related'],
    ['from' => 'o21', 'to' => 'o18', 'type' => 'related'],
    ['from' => 'o16', 'to' => 'o10', 'type' => 'related'],
    ['from' => 'o10', 'to' => 'o16', 'type' => 'related'],
    ['from' => 'o10', 'to' => 'o1', 'type' => 'related'],
    ['from' => 'o1', 'to' => 'o10', 'type' => 'related'],
    // --- close_friends（友達） ---
    ['from' => 'c1', 'to' => 'c2', 'type' => 'deepen'],
    ['from' => 'c3', 'to' => 'c4', 'type' => 'deepen'],
    ['from' => 'c4', 'to' => 'c5', 'type' => 'deepen'],
    ['from' => 'c6', 'to' => 'c7', 'type' => 'deepen'],
    ['from' => 'c8', 'to' => 'c9', 'type' => 'deepen'],
    ['from' => 'c9', 'to' => 'c10', 'type' => 'deepen'],
    ['from' => 'c11', 'to' => 'c12', 'type' => 'deepen'],
    ['from' => 'c13', 'to' => 'c14', 'type' => 'deepen'],
    ['from' => 'c15', 'to' => 'c16', 'type' => 'deepen'],
    ['from' => 'c16', 'to' => 'c17', 'type' => 'deepen'],
    ['from' => 'c1', 'to' => 'c3', 'type' => 'related'],
    ['from' => 'c3', 'to' => 'c1', 'type' => 'related'],
    ['from' => 'c1', 'to' => 'c11', 'type' => 'related'],
    ['from' => 'c11', 'to' => 'c1', 'type' => 'related'],
    ['from' => 'c6', 'to' => 'c8', 'type' => 'related'],
    ['from' => 'c8', 'to' => 'c6', 'type' => 'related'],
    ['from' => 'c13', 'to' => 'c15', 'type' => 'related'],
    ['from' => 'c15', 'to' => 'c13', 'type' => 'related'],
    ['from' => 'c8', 'to' => 'c1', 'type' => 'related'],
    ['from' => 'c1', 'to' => 'c8', 'type' => 'related'],
    // --- first_meeting ---
    ['from' => 'f1', 'to' => 'f2', 'type' => 'deepen'],
    ['from' => 'f3', 'to' => 'f4', 'type' => 'deepen'],
    ['from' => 'f6', 'to' => 'f7', 'type' => 'deepen'],
    ['from' => 'f8', 'to' => 'f9', 'type' => 'deepen'],
    ['from' => 'f5', 'to' => 'f11', 'type' => 'deepen'],
    ['from' => 'f12', 'to' => 'f13', 'type' => 'deepen'],
    ['from' => 'f14', 'to' => 'f15', 'type' => 'deepen'],
    ['from' => 'f1', 'to' => 'f3', 'type' => 'related'],
    ['from' => 'f3', 'to' => 'f1', 'type' => 'related'],
    ['from' => 'f1', 'to' => 'f5', 'type' => 'related'],
    ['from' => 'f5', 'to' => 'f1', 'type' => 'related'],
    ['from' => 'f6', 'to' => 'f12', 'type' => 'related'],
    ['from' => 'f12', 'to' => 'f6', 'type' => 'related'],
    ['from' => 'f8', 'to' => 'f3', 'type' => 'related'],
    ['from' => 'f3', 'to' => 'f8', 'type' => 'related'],
    ['from' => 'f10', 'to' => 'f1', 'type' => 'related'],
    ['from' => 'f1', 'to' => 'f10', 'type' => 'related'],
    ['from' => 'f14', 'to' => 'f3', 'type' => 'related'],
    ['from' => 'f3', 'to' => 'f14', 'type' => 'related'],
    // --- school（学校） ---
    ['from' => 's1', 'to' => 's2', 'type' => 'deepen'],
    ['from' => 's2', 'to' => 's3', 'type' => 'deepen'],
    ['from' => 's4', 'to' => 's5', 'type' => 'deepen'],
    ['from' => 's6', 'to' => 's7', 'type' => 'deepen'],
    ['from' => 's8', 'to' => 's9', 'type' => 'deepen'],
    ['from' => 's10', 'to' => 's11', 'type' => 'deepen'],
    ['from' => 's13', 'to' => 's14', 'type' => 'deepen'],
    ['from' => 's15', 'to' => 's16', 'type' => 'deepen'],
    ['from' => 's18', 'to' => 's19', 'type' => 'deepen'],
    ['from' => 's19', 'to' => 's20', 'type' => 'deepen'],
    ['from' => 's1', 'to' => 's4', 'type' => 'related'],
    ['from' => 's4', 'to' => 's1', 'type' => 'related'],
    ['from' => 's6', 'to' => 's18', 'type' => 'related'],
    ['from' => 's18', 'to' => 's6', 'type' => 'related'],
    ['from' => 's8', 'to' => 's15', 'type' => 'related'],
    ['from' => 's15', 'to' => 's8', 'type' => 'related'],
    ['from' => 's10', 'to' => 's12', 'type' => 'related'],
    ['from' => 's12', 'to' => 's10', 'type' => 'related'],
    ['from' => 's4', 'to' => 's6', 'type' => 'related'],
    ['from' => 's6', 'to' => 's4', 'type' => 'related'],
    // --- romance（恋愛） ---
    ['from' => 'r1', 'to' => 'r2', 'type' => 'deepen'],
    ['from' => 'r2', 'to' => 'r3', 'type' => 'deepen'],
    ['from' => 'r4', 'to' => 'r5', 'type' => 'deepen'],
    ['from' => 'r6', 'to' => 'r7', 'type' => 'deepen'],
    ['from' => 'r8', 'to' => 'r9', 'type' => 'deepen'],
    ['from' => 'r10', 'to' => 'r11', 'type' => 'deepen'],
    ['from' => 'r12', 'to' => 'r13', 'type' => 'deepen'],
    ['from' => 'r15', 'to' => 'r16', 'type' => 'deepen'],
    ['from' => 'r1', 'to' => 'r4', 'type' => 'related'],
    ['from' => 'r4', 'to' => 'r1', 'type' => 'related'],
    ['from' => 'r6', 'to' => 'r10', 'type' => 'related'],
    ['from' => 'r10', 'to' => 'r6', 'type' => 'related'],
    ['from' => 'r8', 'to' => 'r12', 'type' => 'related'],
    ['from' => 'r12', 'to' => 'r8', 'type' => 'related'],
    ['from' => 'r14', 'to' => 'r1', 'type' => 'related'],
    ['from' => 'r1', 'to' => 'r14', 'type' => 'related'],
    ['from' => 'r15', 'to' => 'r10', 'type' => 'related'],
    ['from' => 'r10', 'to' => 'r15', 'type' => 'related'],
    // --- date（デート） ---
    ['from' => 'd1', 'to' => 'd2', 'type' => 'deepen'],
    ['from' => 'd3', 'to' => 'd4', 'type' => 'deepen'],
    ['from' => 'd4', 'to' => 'd5', 'type' => 'deepen'],
    ['from' => 'd6', 'to' => 'd7', 'type' => 'deepen'],
    ['from' => 'd8', 'to' => 'd9', 'type' => 'deepen'],
    ['from' => 'd10', 'to' => 'd11', 'type' => 'deepen'],
    ['from' => 'd13', 'to' => 'd14', 'type' => 'deepen'],
    ['from' => 'd1', 'to' => 'd3', 'type' => 'related'],
    ['from' => 'd3', 'to' => 'd1', 'type' => 'related'],
    ['from' => 'd3', 'to' => 'd6', 'type' => 'related'],
    ['from' => 'd6', 'to' => 'd3', 'type' => 'related'],
    ['from' => 'd8', 'to' => 'd12', 'type' => 'related'],
    ['from' => 'd12', 'to' => 'd8', 'type' => 'related'],
    ['from' => 'd10', 'to' => 'd1', 'type' => 'related'],
    ['from' => 'd1', 'to' => 'd10', 'type' => 'related'],
    ['from' => 'd13', 'to' => 'd1', 'type' => 'related'],
    ['from' => 'd1', 'to' => 'd13', 'type' => 'related'],
    // --- funny（面白い） ---
    ['from' => 'n1', 'to' => 'n2', 'type' => 'deepen'],
    ['from' => 'n3', 'to' => 'n4', 'type' => 'deepen'],
    ['from' => 'n5', 'to' => 'n6', 'type' => 'deepen'],
    ['from' => 'n7', 'to' => 'n8', 'type' => 'deepen'],
    ['from' => 'n9', 'to' => 'n10', 'type' => 'deepen'],
    ['from' => 'n1', 'to' => 'n3', 'type' => 'related'],
    ['from' => 'n3', 'to' => 'n1', 'type' => 'related'],
    ['from' => 'n5', 'to' => 'n7', 'type' => 'related'],
    ['from' => 'n7', 'to' => 'n5', 'type' => 'related'],
    ['from' => 'n9', 'to' => 'n1', 'type' => 'related'],
    ['from' => 'n1', 'to' => 'n9', 'type' => 'related'],
    ['from' => 'n11', 'to' => 'n5', 'type' => 'related'],
    ['from' => 'n5', 'to' => 'n11', 'type' => 'related'],
    // --- omakase ---
    ['from' => 'o23', 'to' => 'o24', 'type' => 'deepen'],
    ['from' => 'o25', 'to' => 'o26', 'type' => 'deepen'],
    ['from' => 'o27', 'to' => 'o28', 'type' => 'deepen'],
    ['from' => 'o28', 'to' => 'o29', 'type' => 'deepen'],
    ['from' => 'o30', 'to' => 'o31', 'type' => 'deepen'],
    ['from' => 'o32', 'to' => 'o33', 'type' => 'deepen'],
    ['from' => 'o34', 'to' => 'o35', 'type' => 'deepen'],
    ['from' => 'o36', 'to' => 'o37', 'type' => 'deepen'],
    ['from' => 'o23', 'to' => 'o25', 'type' => 'related'],
    ['from' => 'o25', 'to' => 'o23', 'type' => 'related'],
    ['from' => 'o27', 'to' => 'o18', 'type' => 'related'],
    ['from' => 'o18', 'to' => 'o27', 'type' => 'related'],
    ['from' => 'o30', 'to' => 'o10', 'type' => 'related'],
    ['from' => 'o10', 'to' => 'o30', 'type' => 'related'],
    ['from' => 'o34', 'to' => 'o21', 'type' => 'related'],
    ['from' => 'o21', 'to' => 'o34', 'type' => 'related'],
    ['from' => 'o36', 'to' => 'o7', 'type' => 'related'],
    ['from' => 'o7', 'to' => 'o36', 'type' => 'related'],
    // --- close_friends（友達） ---
    ['from' => 'c18', 'to' => 'c19', 'type' => 'deepen'],
    ['from' => 'c20', 'to' => 'c21', 'type' => 'deepen'],
    ['from' => 'c22', 'to' => 'c23', 'type' => 'deepen'],
    ['from' => 'c24', 'to' => 'c25', 'type' => 'deepen'],
    ['from' => 'c25', 'to' => 'c26', 'type' => 'deepen'],
    ['from' => 'c27', 'to' => 'c28', 'type' => 'deepen'],
    ['from' => 'c18', 'to' => 'c8', 'type' => 'related'],
    ['from' => 'c8', 'to' => 'c18', 'type' => 'related'],
    ['from' => 'c20', 'to' => 'c11', 'type' => 'related'],
    ['from' => 'c11', 'to' => 'c20', 'type' => 'related'],
    ['from' => 'c27', 'to' => 'c1', 'type' => 'related'],
    ['from' => 'c1', 'to' => 'c27', 'type' => 'related'],
    ['from' => 'c29', 'to' => 'c11', 'type' => 'related'],
    ['from' => 'c11', 'to' => 'c29', 'type' => 'related'],
    // --- first_meeting ---
    ['from' => 'f17', 'to' => 'f18', 'type' => 'deepen'],
    ['from' => 'f19', 'to' => 'f20', 'type' => 'deepen'],
    ['from' => 'f22', 'to' => 'f23', 'type' => 'deepen'],
    ['from' => 'f24', 'to' => 'f25', 'type' => 'deepen'],
    ['from' => 'f16', 'to' => 'f12', 'type' => 'related'],
    ['from' => 'f12', 'to' => 'f16', 'type' => 'related'],
    ['from' => 'f19', 'to' => 'f3', 'type' => 'related'],
    ['from' => 'f3', 'to' => 'f19', 'type' => 'related'],
    ['from' => 'f21', 'to' => 'f5', 'type' => 'related'],
    ['from' => 'f5', 'to' => 'f21', 'type' => 'related'],
    ['from' => 'f22', 'to' => 'f6', 'type' => 'related'],
    ['from' => 'f6', 'to' => 'f22', 'type' => 'related'],
    // --- school（学校） ---
    ['from' => 's21', 'to' => 's22', 'type' => 'deepen'],
    ['from' => 's24', 'to' => 's25', 'type' => 'deepen'],
    ['from' => 's27', 'to' => 's28', 'type' => 'deepen'],
    ['from' => 's30', 'to' => 's31', 'type' => 'deepen'],
    ['from' => 's32', 'to' => 's33', 'type' => 'deepen'],
    ['from' => 's21', 'to' => 's1', 'type' => 'related'],
    ['from' => 's1', 'to' => 's21', 'type' => 'related'],
    ['from' => 's23', 'to' => 's1', 'type' => 'related'],
    ['from' => 's1', 'to' => 's23', 'type' => 'related'],
    ['from' => 's26', 'to' => 's12', 'type' => 'related'],
    ['from' => 's12', 'to' => 's26', 'type' => 'related'],
    ['from' => 's29', 'to' => 's8', 'type' => 'related'],
    ['from' => 's8', 'to' => 's29', 'type' => 'related'],
    ['from' => 's30', 'to' => 's4', 'type' => 'related'],
    ['from' => 's4', 'to' => 's30', 'type' => 'related'],
    // --- romance（恋愛） ---
    ['from' => 'r17', 'to' => 'r18', 'type' => 'deepen'],
    ['from' => 'r20', 'to' => 'r21', 'type' => 'deepen'],
    ['from' => 'r24', 'to' => 'r25', 'type' => 'deepen'],
    ['from' => 'r26', 'to' => 'r27', 'type' => 'deepen'],
    ['from' => 'r17', 'to' => 'r12', 'type' => 'related'],
    ['from' => 'r12', 'to' => 'r17', 'type' => 'related'],
    ['from' => 'r19', 'to' => 'r10', 'type' => 'related'],
    ['from' => 'r10', 'to' => 'r19', 'type' => 'related'],
    ['from' => 'r22', 'to' => 'r14', 'type' => 'related'],
    ['from' => 'r14', 'to' => 'r22', 'type' => 'related'],
    ['from' => 'r23', 'to' => 'r14', 'type' => 'related'],
    ['from' => 'r14', 'to' => 'r23', 'type' => 'related'],
    ['from' => 'r24', 'to' => 'r10', 'type' => 'related'],
    ['from' => 'r10', 'to' => 'r24', 'type' => 'related'],
    // --- date（デート） ---
    ['from' => 'd15', 'to' => 'd16', 'type' => 'deepen'],
    ['from' => 'd22', 'to' => 'd23', 'type' => 'deepen'],
    ['from' => 'd15', 'to' => 'd12', 'type' => 'related'],
    ['from' => 'd12', 'to' => 'd15', 'type' => 'related'],
    ['from' => 'd17', 'to' => 'd13', 'type' => 'related'],
    ['from' => 'd13', 'to' => 'd17', 'type' => 'related'],
    ['from' => 'd18', 'to' => 'd10', 'type' => 'related'],
    ['from' => 'd10', 'to' => 'd18', 'type' => 'related'],
    ['from' => 'd19', 'to' => 'd10', 'type' => 'related'],
    ['from' => 'd10', 'to' => 'd19', 'type' => 'related'],
    ['from' => 'd20', 'to' => 'd6', 'type' => 'related'],
    ['from' => 'd6', 'to' => 'd20', 'type' => 'related'],
    ['from' => 'd21', 'to' => 'd8', 'type' => 'related'],
    ['from' => 'd8', 'to' => 'd21', 'type' => 'related'],
    ['from' => 'd24', 'to' => 'd1', 'type' => 'related'],
    ['from' => 'd1', 'to' => 'd24', 'type' => 'related'],
    // --- funny（面白い） ---
    ['from' => 'n12', 'to' => 'n13', 'type' => 'deepen'],
    ['from' => 'n16', 'to' => 'n17', 'type' => 'deepen'],
    ['from' => 'n18', 'to' => 'n19', 'type' => 'deepen'],
    ['from' => 'n12', 'to' => 'n7', 'type' => 'related'],
    ['from' => 'n7', 'to' => 'n12', 'type' => 'related'],
    ['from' => 'n14', 'to' => 'n9', 'type' => 'related'],
    ['from' => 'n9', 'to' => 'n14', 'type' => 'related'],
    ['from' => 'n15', 'to' => 'n5', 'type' => 'related'],
    ['from' => 'n5', 'to' => 'n15', 'type' => 'related'],
    ['from' => 'n16', 'to' => 'n5', 'type' => 'related'],
    ['from' => 'n5', 'to' => 'n16', 'type' => 'related'],
    ['from' => 'n18', 'to' => 'n3', 'type' => 'related'],
    ['from' => 'n3', 'to' => 'n18', 'type' => 'related'],
];

$pdo->beginTransaction();

try {
    $categoryIdByKey = [];
    $catStmt = $pdo->prepare(
        'INSERT INTO categories (`key`, label, sort_order) VALUES (:key, :label, :sort_order)
         ON DUPLICATE KEY UPDATE label = VALUES(label), sort_order = VALUES(sort_order)'
    );
    foreach ($categories as $c) {
        $catStmt->execute([':key' => $c['key'], ':label' => $c['label'], ':sort_order' => $c['sort_order']]);
        $idStmt = $pdo->prepare('SELECT id FROM categories WHERE `key` = :key');
        $idStmt->execute([':key' => $c['key']]);
        $categoryIdByKey[$c['key']] = (int) $idStmt->fetchColumn();
    }

    $topicIdByKey = [];
    $topicStmt = $pdo->prepare(
        'INSERT INTO topics (body, category_id, depth, is_starter, status, source)
         VALUES (:body, :category_id, :depth, :is_starter, "published", "seed")'
    );
    foreach ($topics as $t) {
        $topicStmt->execute([
            ':body' => $t['body'],
            ':category_id' => $categoryIdByKey[$t['category']],
            ':depth' => $t['depth'],
            ':is_starter' => !empty($t['is_starter']) ? 1 : 0,
        ]);
        $topicIdByKey[$t['key']] = (int) $pdo->lastInsertId();
    }

    $relStmt = $pdo->prepare(
        'INSERT INTO topic_relations (from_topic_id, to_topic_id, relation_type)
         VALUES (:from_id, :to_id, :type)'
    );
    foreach ($relations as $r) {
        $relStmt->execute([
            ':from_id' => $topicIdByKey[$r['from']],
            ':to_id' => $topicIdByKey[$r['to']],
            ':type' => $r['type'],
        ]);
    }

    $pdo->commit();
    echo 'Seeded ' . count($categories) . ' categories, ' . count($topics) . ' topics, '
        . count($relations) . " relations.\n";
} catch (Throwable $e) {
    $pdo->rollBack();
    fwrite(STDERR, 'Seed failed: ' . $e->getMessage() . "\n");
    exit(1);
}
